/*******************************************************************************

 *  File name: UserParameters.c
 *  File creation date/time: 07.02.2022 - 15:09:02
 *  Description: User parameters with related text resources and meta data

 *  IMPORTANT
 *  DO NOT EDIT THIS FILE!
 *  This file is generated from an Excel document by a Powershell script.

 *  Excel document: UserParameters.xlsx
 *  Author: Aravindh Vishnu
 *  Revision Number: 1
 *  Creation Time: 01/26/2022 11:58:50
 *  Last Save Time: 02/06/2022 18:50:44

 *  Powershell script: UserParameters.ps1
 *  Author: Aravindh Vishnu
 *  Revision Number: 1
 *  Creation Time: 01/31/2022 18:49:39
 *  Last Save Time: 02/07/2022 15:08:56

 *******************************************************************************
 */

#include "UserParameters.h"

const USER_PARAM_TYPE userParameters[TOTAL_PARAMETERS] =
{
    {
        "START_STOP_MODE_BLOCK",
        21,
        0,
        {
            "Start/Stop mode",
            "Start/Stopp funktion",
            "Start/Stopp-Modus",
            "Mode démarrage/arrêt",
            "Modo de inicio/parada"
        },
        (unit)0,
        (data)0,
        0,
        0,
        0,
        0
    },
    {
        "START_MODE",
        21,
        1,
        {
            "Start mode",
            "Startfunktion",
            "Startmodus",
            "Mode de démarrage",
            "Modo de inicio"
        },
        NO_UNIT,
        TYPE_UINT8,
        2,
        0,
        2,
        0
    },
    {
        "MAG_TIME",
        21,
        2,
        {
            "Magnetization time",
            "Magnetiseringstiden",
            "Magnetisierungszeit",
            "Temps de magnétisation",
            "Tiempo de magnetización"
        },
        MS,
        TYPE_UINT16,
        500,
        0,
        10000,
        0
    },
    {
        "STOP_MODE",
        21,
        3,
        {
            "Stop mode",
            "Stoppfunktion",
            "Stop-modus",
            "Mode d'arrêt",
            "Modo de parada"
        },
        NO_UNIT,
        TYPE_UINT8,
        0,
        0,
        2,
        0
    },
    {
        "E_STOP_MODE",
        21,
        4,
        {
            "Emergency stop mode",
            "Nödstoppfunktion",
            "Not-Aus-Modus",
            "Mode d'arrêt d'urgence",
            "Modo de parada de emergencia"
        },
        NO_UNIT,
        TYPE_UINT8,
        0,
        0,
        2,
        0
    },
    {
        "E_STOP_SOURCE",
        21,
        5,
        {
            "Emergency stop source",
            "Nödstoppskälla",
            "Not-Aus-Quelle",
            "Source d'arrêt d'urgence",
            "Fuente de parada de emergencia"
        },
        NO_UNIT,
        TYPE_UINT8,
        1,
        0,
        12,
        0
    },
    {
        "ZERO_SPEED_LIMIT",
        21,
        6,
        {
            "Zero speed limit",
            "Stillaståendenivå",
            "Geschwindigkeitsbegrenzung Null",
            "Limite de vitesse nulle",
            "Límite de velocidad cero"
        },
        RPM,
        TYPE_FLOAT32,
        30,
        0,
        30000,
        2
    },
    {
        "ZERO_SPEED_DELAY",
        21,
        7,
        {
            "Zero speed delay",
            "Stillastående fördröjning",
            "Nullgeschwindigkeitsverzögerung",
            "Délai de vitesse nulle",
            "Retardo de velocidad cero"
        },
        MS,
        TYPE_UINT16,
        0,
        0,
        30000,
        0
    },
    {
        "DC_I_CTRL",
        21,
        8,
        {
            "DC current control",
            "DC strömkontroll",
            "DC-Stromregelung",
            "Contrôle du courant continu",
            "Control de corriente continua"
        },
        NO_UNIT,
        TYPE_UINT16,
        0,
        0,
        65535,
        0
    },
    {
        "DC_HOLD_SPEED",
        21,
        9,
        {
            "DC hold speed",
            "DC håll varvtal",
            "DC-Haltegeschwindigkeit",
            "Vitesse de maintien CC",
            "Velocidad de mantenimiento de CC"
        },
        RPM,
        TYPE_FLOAT32,
        5,
        0,
        1000,
        1
    },
    {
        "DC_I_REF",
        21,
        10,
        {
            "DC current reference",
            "DC strömreferens",
            "Gleichstromreferenz",
            "Référence de courant continu",
            "Referencia de corriente CC"
        },
        PERCENT,
        TYPE_UINT8,
        30,
        0,
        100,
        0
    },
    {
        "POST_MAG_TIME",
        21,
        11,
        {
            "Post magnetization time",
            "Eftermagnetiseringstid",
            "Nachmagnetisierungszeit",
            "Temps de post magnétisation",
            "Tiempo posterior a la magnetización"
        },
        MS,
        TYPE_UINT16,
        0,
        0,
        30000,
        0
    },
    {
        "AUTOPHASING_MODE",
        21,
        13,
        {
            "Autophasing mode",
            "Autofasfunktion",
            "Autophasing-Modus",
            "Mode de mise en phase automatique",
            "Modo de puesta en fase automática"
        },
        NO_UNIT,
        TYPE_UINT8,
        0,
        0,
        2,
        0
    },
    {
        "AUTO_RESTART_TIME",
        21,
        18,
        {
            "Auto restart time",
            "Automatisk omstartstid",
            "Automatische Neustartzeit",
            "Temps de redémarrage automatique",
            "Tiempo de reinicio automático"
        },
        S,
        TYPE_FLOAT32,
        0,
        0,
        5,
        1
    },
    {
        "OPERATION_MODE_BLOCK",
        19,
        0,
        {
            "Operation mode",
            "Driftsfunktion",
            "Betriebsmodus",
            "Mode de fonctionnement",
            "Modo de operación"
        },
        (unit)0,
        (data)0,
        0,
        0,
        0,
        0
    },
    {
        "ACT_OP_MODE",
        19,
        1,
        {
            "Actual operation mode",
            "Aktuell driftsfunktion",
            "Aktueller Betriebsmodus",
            "Mode de fonctionnement réel",
            "Modo de operación real"
        },
        NO_UNIT,
        TYPE_UINT8,
        1,
        1,
        20,
        0
    },
    {
        "EXT1_EXT2_SEL",
        19,
        11,
        {
            "Ext1/EXT2 selection",
            "Ext1/EXT2 val",
            "Ext1/EXT2-Auswahl",
            "Sélection Ext1/EXT2",
            "Selección Ext1/EXT2"
        },
        NO_UNIT,
        TYPE_UINT8,
        0,
        0,
        12,
        0
    },
    {
        "EXT1_CTRL_MODE_1",
        19,
        12,
        {
            "Ext1 control mode 1",
            "Ext1 kontrollfunktion 1",
            "Ext1 Steuermodus 1",
            "Ext1 mode de contrôle 1",
            "Ext1 modo de control 1"
        },
        NO_UNIT,
        TYPE_UINT8,
        2,
        1,
        6,
        0
    },
    {
        "EXT2_CTRL_MODE_1",
        19,
        14,
        {
            "Ext2 control mode 1",
            "Ext2 kontrollfunktion 1",
            "Ext2 Steuermodus 1",
            "Ext2 mode de contrôle 1",
            "Ext2 modo de control 1"
        },
        NO_UNIT,
        TYPE_UINT8,
        2,
        1,
        6,
        0
    },
    {
        "LOCAL_CTRL_MODE",
        19,
        16,
        {
            "Local control mode",
            "Lokal kontrollfunktion",
            "Lokaler Steuermodus",
            "Mode de contrôle local",
            "Modo de control local"
        },
        NO_UNIT,
        TYPE_UINT8,
        0,
        0,
        1,
        0
    },
    {
        "LOCAL_CTRL_DISABLE",
        19,
        17,
        {
            "Local control disable",
            "Lokal kontrollavstängning",
            "Deaktivierung der lokalen Steuerung",
            "Désactivation de la commande locale",
            "Inhabilitar control local"
        },
        NO_UNIT,
        TYPE_UINT8,
        0,
        0,
        1,
        0
    },
    {
        "SCALAR_CTRL_REF_UNIT",
        19,
        20,
        {
            "Scalar control reference unit",
            "Skalär kontrollreferensenhet",
            "Referenzeinheit für die Skalarsteuerung",
            "Unité de référence de contrôle scalaire",
            "Unidad de referencia de control escalar"
        },
        NO_UNIT,
        TYPE_UINT8,
        1,
        0,
        1,
        0
    }
};
