/*******************************************************************************

 *  File name: UserParameters.h
 *  File creation date/time: 07.02.2022 - 15:09:02
 *  Description: User parameters with related text resources and meta data

 *  IMPORTANT
 *  DO NOT EDIT THIS FILE!
 *  This file is generated from an Excel document by a Powershell script.

 *  Excel document: UserParameters.xlsx
 *  Author: Aravindh Vishnu
 *  Revision Number: 1
 *  Creation Time: 01/26/2022 11:58:50
 *  Last Save Time: 02/06/2022 18:50:44

 *  Powershell script: UserParameters.ps1
 *  Author: Aravindh Vishnu
 *  Revision Number: 1
 *  Creation Time: 01/31/2022 18:49:39
 *  Last Save Time: 02/07/2022 15:08:56

 *******************************************************************************
 */

#include "stdint.h"
#include "stdlib.h"
#include "string.h"

typedef enum unitType
{
    NO_UNIT = 0,
    MS,
    S,
    RPM,
    PERCENT,
    NBR_OF_UNITS
} unit;

typedef enum dataType
{
    TYPE_UINT8 = 0,
    TYPE_INT8,
    TYPE_UINT16,
    TYPE_INT16,
    TYPE_UINT32,
    TYPE_INT32,
    TYPE_FLOAT32,
    TYPE_FLOAT64,
    NBR_OF_DATATYPES
} data;

typedef struct
{
    char const * const shortName;
    uint8_t block;
    uint8_t field;
    char const * const text[5];
    unit unitType;
    data dataType;
    int32_t defaultValue;
    int32_t minValue;
    int32_t maxValue;
    uint8_t nbrOfDecimals;
} USER_PARAM_TYPE;

#define START_STOP_MODE_BLOCK 0
#define START_MODE 1
#define MAG_TIME 2
#define STOP_MODE 3
#define E_STOP_MODE 4
#define E_STOP_SOURCE 5
#define ZERO_SPEED_LIMIT 6
#define ZERO_SPEED_DELAY 7
#define DC_I_CTRL 8
#define DC_HOLD_SPEED 9
#define DC_I_REF 10
#define POST_MAG_TIME 11
#define AUTOPHASING_MODE 12
#define AUTO_RESTART_TIME 13
#define OPERATION_MODE_BLOCK 14
#define ACT_OP_MODE 15
#define EXT1_EXT2_SEL 16
#define EXT1_CTRL_MODE_1 17
#define EXT2_CTRL_MODE_1 18
#define LOCAL_CTRL_MODE 19
#define LOCAL_CTRL_DISABLE 20
#define SCALAR_CTRL_REF_UNIT 21
#define TOTAL_PARAMETERS 22

extern const USER_PARAM_TYPE userParameters[TOTAL_PARAMETERS];
